extends:
  - standard
  - plugin:react/recommended
env:
  browser: yes
  node: yes
parser: babel-eslint
plugins:
  - standard
  - promise
  - react
settings:
  react:
    pragma: h
rules:
  react/no-unknown-property: off
